// <auto-generated />
namespace finalproject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class step5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(step5));
        
        string IMigrationMetadata.Id
        {
            get { return "202206160035094_step5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
